[[contributing-to-the-git-client-plugin]]
= Contributing to the Git Client Plugin

The git client plugin implements the link:https://plugins.jenkins.io/scm-api[Jenkins SCM API].
Refer to the SCM API documentation for link:https://github.com/jenkinsci/scm-api-plugin/blob/master/docs/implementation.adoc#naming-your-plugin[plugin naming conventions]
and for the link:https://github.com/jenkinsci/scm-api-plugin/blob/master/CONTRIBUTING.md#add-to-core-or-create-extension-plugin[preferred locations of new functionality].

== Preparing a pull request

Plugin source code is hosted on link:https://github.com/jenkinsci/git-client-plugin[GitHub].
New feature proposals and bug fix proposals should be submitted as link:https://help.github.com/articles/creating-a-pull-request[GitHub pull requests].
Your pull request will be evaluated by the link:https://ci.jenkins.io/job/Plugins/job/git-client-plugin/[Jenkins job].

Before submitting your change, please assure that you've added tests which verify your change.
There have been many developers involved in the git client plugin and there are many, many users who depend on the git client plugin.
Tests help us assure that we're delivering a reliable plugin, and that we've communicated our intent to other developers as executable descriptions of plugin behavior.

=== Compiling and testing the plugin

Compile and run the plugin automated tests on Java 8 or Java 11 with:

* `mvn clean verify`

Run the plugin inside a Jenkins environment with the link:https://jenkinsci.github.io/maven-hpi-plugin/run-mojo.html[maven hpi plugin]:

* `mvn -Djetty.port=8080 hpi:run`

=== Code coverage reporting

Code coverage reporting is available as a maven target.
Please improve code coverage with tests when you submit.

* `mvn -P enable-jacoco clean install jacoco:report` to report code coverage

=== Spotbugs checks

Please don't introduce new spotbugs output.

* `mvn spotbugs:check` to analyze project using link:https://spotbugs.github.io/[Spotbugs].
* `mvn spotbugs:gui` to review Spotbugs report using GUI

Code formatting in the git client plugin varies between files.
Try to maintain reasonable consistency with the existing files where feasible.

Please *don't reformat a file* without discussing with the current maintainers.
There are many closed pull requests with label 'link:https://github.com/jenkinsci/git-client-plugin/milestone/2?closed=1[Later]' that may develop conflicts due to whitespace changes.

New code should follow the link:https://github.com/jenkinsci/scm-api-plugin/blob/master/CONTRIBUTING.md#code-style-guidelines[SCM API code style guidelines].

[[pull-request-review]]
== Reviewing Pull Requests

Maintainers triage pull requests by reviewing them and by assigning labels.
Release drafter uses the labels to automate link:https://github.com/jenkinsci/git-client-plugin/releases[release notes].
link:Priorities.adoc#git-client-plugin-development-priorities[Prioritization] uses the labels to group relevant pull requests.

Others are encouraged to review pull requests, test pull request builds, and report their results in the pull request.
Refer to the link:Priorities.adoc#priorities[maintainer's priority list] for topics the plugin maintainers are considering.

=== Testing a Pull Request Build

Pull request builds merge the most recent changes from their target branch with the change proposed in the pull request.
They can be downloaded from ci.jenkins.io and used to test the pull request.
Steps to test a pull request build are:

. *Find the pull request on link:https://github.com/jenkinsci/git-client-plugin/pulls[GitHub]* - for example, link:https://github.com/jenkinsci/git-client-plugin/pull/467[pull request 467]
. *Find the link:https://ci.jenkins.io/job/Plugins/job/git-client-plugin/view/change-requests/[ci.jenkins.io] artifacts for that pull request* from the link to the link:https://ci.jenkins.io/job/Plugins/job/git-client-plugin/job/PR-676/lastSuccessfulBuild/[artifacts in the Jenkins job] in "*Show all checks*"
. *Download the `hpi` file* (like `git-client-3.0.1-rc3444.b3d767e3d46a.hpi`) to your computer
. *Upload the `hpi` file* to Jenkins from the Jenkins Plugin Manager
. *Restart your Jenkins* and you're ready to test

[[bug-triage]]
== Reviewing Bug Reports

Git client plugin bug reports are assigned to one of the maintainers by default.
link:https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open)%20AND%20component%20%3D%20git-client-plugin%20and%20assignee%20in%20(rsandell%2Cmarkewaite%2Cfcojfernandez)[Open bug reports] assigned to a maintainer are assumed to have not been reviewed.
When a maintainer completes review of an issue, they include a comment on the bug report and set the 'Assignee' to 'Unassigned'.

Others are welcome to review bug reports, comment on the results of the review, and set the 'Assignee' to 'Unassigned'.
Typical bug review tasks include:

* Review summary and description
* Attempt to duplicate the issue
* Add a comment with results of the attempt to duplicate the issue

[[jmh-benchmarks]]
== Java Microbenchmark Harness

Git client plugin includes link:https://openjdk.java.net/projects/code-tools/jmh/[Java Microbenchmark Harness (JMH)] benchmark tests to compare the performance of command line git and JGit.
Run the benchmarks with the command:

* `mvn -P jmh-benchmark test`
