version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_reviewers:
      - "MarkEWaite"
    default_labels:
      - "dependencies"
